version: '3.2'
services:
  mysql:
    image: mysql:5.5
    labels:
      - "com.docker.ucp.access.label=/Shared/Legacy/webcoe-dev"
      - "com.docker.ucp.access.owner=f_webcoe_user"
      - "NOLOGSPOUT"
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=directus
    volumes:
      - "db:/var/lib/mysql"
  directus:
    depends_on:
       - mysql
    image: getdirectus/directus:6.4
    labels:
      - "com.docker.ucp.access.label=/Shared/Legacy/webcoe-dev"
      - "com.docker.ucp.access.owner=f_webcoe_user"
      - "NOLOGSPOUT"
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
    ports:
     - "21200:8080"
    volumes:
      - assets:/var/www/html/storage
    environment:
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_DATABASE=directus
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
     - MYSQL_ENV_MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_USER=directus
    # If you use docker for dev or want to test without opcache - disable with env var
    #  - PHP_OPCACHE_ENABLED=false
volumes:
  assets:
  db:
